### ISSUE TITLE
数学公式拷贝到微信公众号编辑器之后显示异常

### ISSUE THREAD

**Issue by ShannonZ** [maqi1520/mdx-editor#14]
MDX中显示正常
![image](https://user-images.githubusercontent.com/7865691/198937420-72f7fbac-1b23-4c7e-9fb6-e9b4110e7555.png)

贴到微信公众号编辑器中之后：
![image](https://user-images.githubusercontent.com/7865691/198937497-73c1e880-90e9-4f87-bf5f-2a8703c4199b.png)

**Comment by maqi1520** [comment]
没想到好的解决方法

**Comment by maqi1520** [comment]
使用 mathjax 解决，客户端下载 0.9.4 版本
