### ISSUE TITLE
小马哥 ~看到仓库中的代码基本都是 0 注释，是有什么方法可以在 commit 的时候删除注释嘛~还是就是这样的😅

### ISSUE THREAD

**Issue by wangrongding** [maqi1520/mdx-editor#18]
挺好奇的~ 如果有这种方案想学习一下🧐

**Comment by maqi1520** [comment]
这个项目我自己维护，没写注释。 如果要实现这样的方式 可以使用 [jscodeshift](https://www.npmjs.com/package/jscodeshift)+  [husky](https://www.npmjs.com/package/husky)，合并分支的时候自动去除，应该可以实现。

**Comment by maqi1520** [comment]
这个项目是在 https://play.tailwindcss.com/  基础上改的。

**Comment by wangrongding** [comment]
> 这个项目我自己维护，没写注释。 如果要实现这样的方式 可以使用 [jscodeshift](https://www.npmjs.com/package/jscodeshift)+ [husky](https://www.npmjs.com/package/husky)，合并分支的时候自动去除，应该可以实现。

学到了，感谢小马哥🌸
