### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by RANSAA** [maqi1520/mdx-editor#21]
设置工作目录后关闭重新打开后空白
还有存储是怎么回事每次都弹出选择框，难道不能支持自动保存？
新建文件在哪里怎么找不到
有HTML标签直接渲染错误
macos菜单栏无用选项太多

**Comment by maqi1520** [comment]
感谢您的反馈
- 1、设置工作目录后关闭重新打开后空白
工作目录目前使用 localStroage 存储，我的电脑 Mac M1 没遇到问题，请提供你的系统版本，以及截图或者录屏
- 还有存储是怎么回事每次都弹出选择框，难道不能支持自动保存？
支持自动保存的，但首次打开的时候会存在这个问题，这个会在 0.4.6 修复
- 新建文件在哪里怎么找不到
会在 0.4.6 增加菜单
- 有HTML标签直接渲染错误
需要确保是 jsx, 而不是 html

**错误写法**
```
<div style="">text</div>
```
![CleanShot 2023-07-18 at 09 20 23@2x](https://github.com/maqi1520/mdx-editor/assets/9312044/aab4f9aa-bdb2-4dfc-86ed-ab8dbf2873d1)
编译错误会有提醒

**正确写法**
```
<div style={{color:'red'}}>text</div>
```
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/1b8801a0-fb82-4c1b-9f14-39b659aa4786)

- macos菜单栏无用选项太多
会在 0.4.6 清除无用菜单栏

**Comment by maqi1520** [comment]
0.4.6 已发布

**Comment by maqi1520** [comment]
还有些问题

**Comment by maqi1520** [comment]
0.4.7
