### ISSUE TITLE
请大佬开发mac silcon的版本

### ISSUE THREAD

**Issue by justincnn** [maqi1520/mdx-editor#22]
用了x86版本，很喜欢，

洁癖患者还是求大佬可以编译一个mac slicon的版本，

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases/download/v0.4.7/MDX.Editor_0.4.7_x64.dmg
 这个不能安装吗？

**Comment by maqi1520** [comment]
可以看下 最新版本 https://github.com/maqi1520/mdx-editor/releases

**Comment by legend80s** [comment]
MDX.Editor_0.7.2_x64.dmg

非常棒的工具，但是安装报错这个，符合预期不？需要安装 Rosetta？

<img width="480" alt="image" src="https://github.com/maqi1520/mdx-editor/assets/8603442/19bbd93e-9724-4e29-93e8-7f212f9975da">

**Comment by legend80s** [comment]
M1 芯片

**Comment by maqi1520** [comment]
M1 装这个版本 https://github.com/maqi1520/mdx-editor/releases/download/v0.7.2/MDX.Editor_0.7.2_aarch64.dmg

**Comment by legend80s** [comment]
ok 多谢 我试试

**Comment by legend80s** [comment]
不行 打开一片空白 MacBook Air Monterey 12.4 M1

**Comment by maqi1520** [comment]
> 不行 打开一片空白 MacBook Air Monterey 12.4 M1


我怀疑是兼容性的问题，因为在我的电脑上看，是可以运行的，我的系统是 mac M1 macOs 13.4.1， 如果可以的话请安装这个版本，然后右键打开控制台，然后截图回复我，帮我排查问题，万分感谢。

![image](https://github.com/maqi1520/mdx-editor/assets/9312044/2978110b-6787-44ff-bc4c-3389a28da054)
[MDX Editor_0.7.3_aarch64.dmg.zip](https://github.com/maqi1520/mdx-editor/files/13715162/MDX.Editor_0.7.3_aarch64.dmg.zip)

**Comment by maqi1520** [comment]
#44

**Comment by legend80s** [comment]
已升级 0.7.3 右键只有 Reload

**Comment by maqi1520** [comment]
> 已升级 0.7.3 右键只有 Reload

下载上面的zip 文件，
