### ISSUE TITLE
之前的问题依然没有解决

### ISSUE THREAD

**Issue by RANSAA** [maqi1520/mdx-editor#23]
1. 设置工作目录后白板，且无法重新设置
2. H5标签渲染问题：比如输入<br>理想的结果是换行，如果不支持则应该直接显示；  结果却是直接出现渲染失败，这显然是很大的一个问题。这样就导致恨得MD文档渲染失败。

![截屏2023-07-29 23 14 07](https://github.com/maqi1520/mdx-editor/assets/10286613/37012cfd-cf26-4808-9ad7-f66f66d9ea05)

**Comment by maqi1520** [comment]
第一个问题，我这边没复现
第二个问题，可以说不是问题，但也是很大的问题，mdx 很多人用法不知道 怎么使用，`<br>` 是错误的 要改成 `<br/>`

**Comment by maqi1520** [comment]
可以加我 微信：maqi1520
