### ISSUE TITLE
Cannot set property marked of #<Object> which has only a getter

### ISSUE THREAD

**Issue by impohcom** [maqi1520/mdx-editor#27]
Cannot set property marked of #<Object> which has only a getter
TypeError: Cannot set property marked of #<Object> which has only a getter at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js:2358:25) at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js:27:17) at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js:28:7) at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js:2371:3) at ./node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (http://localhost:3000/_next/static/chunks/src_components_EditorDesktop_js.js:2675:1) at options.factory (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:676:31) at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:37:33) at fn (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:331:21) at eval (webpack-internal:///./node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js:19:83) at ./node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js (http://localhost:3000/_next/static/chunks/src_components_EditorDesktop_js.js:1707:1) at options.factory (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:676:31) at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:37:33) at fn (http://localhost:3000/_next/static/chunks/webpack.js?ts=1691938615096:331:21) at eval (webpack-

**Comment by maqi1520** [comment]
请具体描述问题
