### ISSUE TITLE
进入Web版时页面出错，日志错误缺少css字段。

### ISSUE THREAD

**Issue by lpreterite** [maqi1520/mdx-editor#31]
页面直接无法渲染出来，在结合之前微软Windows下邮件应用的同类情况，我怀疑是应用缓存数据格式与新版本的应用并不兼容导致的此类问题。

后来清除了应用本地缓存后，能成功进入界面。

**Comment by maqi1520** [comment]
感谢反馈，目前存储是是使用本地缓存，但您您说的问题我无法复现，也没有办法修改
