### ISSUE TITLE
Would you consider supporting Mermaid syntax?

### ISSUE THREAD

**Issue by yyong008** [maqi1520/mdx-editor#33]
Sometimes there is a need to draw flowcharts. Have you considered supporting Mermaid-related syntax?

**Comment by maqi1520** [comment]
It's  supported
 
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/b9d70b49-5fa7-4eef-876c-a46fbedcce51)


![image](https://github.com/maqi1520/mdx-editor/assets/9312044/fe794e5f-b094-4a08-94c5-f65b8f8db560)
