### ISSUE TITLE
Mac版本没有导出pdf的工功能

### ISSUE THREAD

**Issue by MrNickwm** [maqi1520/mdx-editor#37]
Mac版本上可以save as html，但是没有找到导出PDF的功能

**Comment by maqi1520** [comment]
是的，可以点击分享按钮，使用 web版 导出，mac 版这个功能正在开发中

**Comment by blackstar-baba** [comment]
> Mac版本上可以save as html，但是没有找到导出PDF的功能

+1

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases 下载最新版
使用打印功能实现 html 转 pdf
