### ISSUE TITLE
能否增加微信的默认样式？

### ISSUE THREAD

**Issue by Jackeriss** [maqi1520/mdx-editor#40]
目前的几套样式主题和微信原本的默认样式区别比较大，如果不需要还得一项一项覆盖，希望能增加使用微信原本默认样式的选项，这样自定义样式的时候不用覆盖太多。

**Comment by maqi1520** [comment]
欢迎贡献默认主题 css 代码

**Comment by maqi1520** [comment]
能否提供一个标准的微信文章页，作为默认页样式参考？

**Comment by maqi1520** [comment]
桌面客户端 v0.9.1 支持了完全自定义样式；

第一步：新建目录 plugins/themes
第二步：写 css 或者 js
第三步：在文档头部 加上 theme 属性，theme  的值，就是 css 文件名
