### ISSUE TITLE
windows无法自动安装新版本

### ISSUE THREAD

**Issue by winner106** [maqi1520/mdx-editor#41]
弹窗询问, 点"是"确认, 重启软件, 继续弹窗, ......, 循环
![image](https://github.com/maqi1520/mdx-editor/assets/50519642/8e8dfb4b-dbc2-4e95-b6fd-37f07b360bab)

一直没法安装成功, 我的网络没有问题.

**Comment by maqi1520** [comment]
目前是托管在github ，可能需要全局翻墙，建议手动下载
