### ISSUE TITLE
实时统计字数有bug

### ISSUE THREAD

**Issue by Akuns** [maqi1520/mdx-editor#42]
如图，百分百复现。
<img width="1536" alt="image" src="https://github.com/maqi1520/mdx-editor/assets/19256829/aff6c771-85a6-41a4-bca5-66f01e51a5c9">

**Comment by maqi1520** [comment]
统计的是字和单词

**Comment by Akuns** [comment]
@maqi1520 作为给微信文章排版的工具，改成字符长度是否更合理，在微信公众号编辑器里也是统计字符长度

> 统计的是字和单词

**Comment by maqi1520** [comment]
@Akuns 公众号也是字数

**Comment by Akuns** [comment]
> @Akuns 公众号也是字数

是我搞错了，装了插件，插件是按字符长度统计的
