### ISSUE TITLE
此种颜色的css样式在typora中可以支持，但是换到MDX中无法支持

### ISSUE THREAD

**Issue by Runnerxr** [maqi1520/mdx-editor#45]
以下这段css格式的文本示例在typora中可以显示，但是切换到MDX中就无法识别了，有办法解决嘛
<span style="color:#FF0000;">文本内容示例</span>

**Comment by Runnerxr** [comment]
<span style="color:#FF0000;">文本示例</span>。
![Uploading 问题.png…]()

**Comment by maqi1520** [comment]
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/f353c4b0-f91f-4801-b803-988d4e7dfab2)
更新了下，打开这个就可以

**Comment by Runnerxr** [comment]
有帮助，谢谢！！


| |
熊锐
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年1月2日 20:13 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [maqi1520/mdx-editor] 此种颜色的css样式在typora中可以支持，但是换到MDX中无法支持 (Issue #45) |

image.png (view on web)
更新了下，打开这个就可以
