### ISSUE TITLE
代码粘贴格式错误

### ISSUE THREAD

**Issue by xu-mengnan** [maqi1520/mdx-editor#46]
粘贴一段markdown下的代码，然后复制出来，微信识别不出是代码段，按照文字渲染，导致同一行的代码强制换行，多行展示。

**Comment by maqi1520** [comment]
web 端可以点分享，会有一个url地址，贴出来看下

**Comment by xu-mengnan** [comment]
> web 端可以点分享，会有一个url地址，贴出来看下

可以看下这个例子，代码段部分。
https://editor.runjs.cool/65964e4d8b0da43e66541908

**Comment by maqi1520** [comment]
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/485166e0-70e8-41fb-9605-d9f7d038b7d4)
我这边看没问题
