### ISSUE TITLE
写了一篇文章,发现复制的时候一直转圈圈

### ISSUE THREAD

**Issue by Fowindy** [maqi1520/mdx-editor#49]
![Clip_2024-01-19_17-54-08](https://github.com/maqi1520/mdx-editor/assets/45205351/d85e795b-f6a8-40a0-bf17-dee9d25cb093)
文章链接如下:使用的是初夏风格的皮肤
https://www.wolai.com/fowindy/bunUPVM2KyoMT3zaPazQPm
能帮我看一下什么原因吗?还有目前二级标题可以自动排序,三级标题能否也排序呢,比如二级是1.三级就1.1或1.2等等
十分感谢

**Comment by maqi1520** [comment]
https://editor.runjs.cool/65aa67496e5d2ddb51351eee?file=config 自动编号需要使用 js 实现，可以看下 150 行代码

windows 请升级最新版本，试复制功能是否还有问题。
