### ISSUE TITLE
代码中高亮支持

### ISSUE THREAD

**Issue by hua1995116** [maqi1520/mdx-editor#5]
效果类似：
https://zh-hans.reactjs.org/docs/lists-and-keys.html

<img width="938" alt="image" src="https://user-images.githubusercontent.com/12070073/162678332-d5cab57c-9a04-4975-b1e7-6fdea875e201.png">

**Comment by maqi1520** [comment]
在计划内了

**Comment by maqi1520** [comment]
语法高亮
在语法前面加 diff- 比如 diff-js、diff-jsx, diff-ts，代码前面可以加 +,-,就可以高亮代码了

下面是默认样式，可以在 css 中覆盖

![image](https://user-images.githubusercontent.com/9312044/162939475-98618367-695e-40b3-b46a-d5f962db57c1.png)

预览地址

https://editor.runjs.cool/625550658cc5730001809f0c
