### ISSUE TITLE
如何生成文章目录？

### ISSUE THREAD

**Issue by xiekunwhy** [maqi1520/mdx-editor#53]
您好，

我看 https://editor.runjs.cool/ 说可以生成文章目录，但我并没有找到相应的方法（除非自己手动建目录），比如有道笔记或者马克飞象是用[TOC]来生成目录的，mdx是用哪个代码来生成目录？

另外，mdx可以支持回车即换行而不用空两格回车或者回车两次才换行吗，像马克飞象印象笔记那样？

祝好！

**Comment by maqi1520** [comment]
```md
## TOC
```
第二点不支持
