### ISSUE TITLE
目前的版本图片格式无法兼容typora

### ISSUE THREAD

**Issue by Asura88** [maqi1520/mdx-editor#55]
typora里面图片本地格式 是 ./img/

我们这个软件本地格式 是 /img/

区别在于一个. typora无法正确识别图片

**Comment by maqi1520** [comment]
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/a3337d65-f0c7-477c-bd32-e62b6384a3eb)
都可以识别，默认是 /img/ 开通，与 obsidian 实现相同

typora 中的图片目录我不知道怎么设置，你可以详细截图我看下

**Comment by Asura88** [comment]
你这个默认是没有.的我把图片粘贴进去生成的目录没有.typra不识别

**Comment by maqi1520** [comment]
在 [0.7.8](https://github.com/maqi1520/mdx-editor/releases/tag/app-v0.7.8) 版本修复
