### ISSUE TITLE
文档设置默认的主题和插件 【feature request】

### ISSUE THREAD

**Issue by tthaha110** [maqi1520/mdx-editor#60]
首先感谢提供这个工具，很符合我的心意，比起思源笔记定制化更高更随意。简单试用了下，发现切换md文档，使用的是全局设置。如果所有的文件想要的效果一致道还好，如果希望每个文件的风格不一样，每次都需要单独设置，不是很方便。

# 设想
在文档头部添加meta信息，可以设置主题，渲染方式。打开文档默认就能使用这些信息进行渲染，如果没有设置就使用全局的设置。

# 扩展
全局可以设置插件【固定目录】--主题插件、react组件、jsx组件之类的，也可以在meta中制定使用到的组件。如果是全局组件就直接导入渲染，大大增加了内容的表现力。

**Comment by maqi1520** [comment]
很棒的创意，一起参与建设吗？

**Comment by maqi1520** [comment]
请尝试 [v0.9.0](https://github.com/maqi1520/mdx-editor/releases/tag/app-v0.9.0) 版本
使用在项目目录中新建 `plugins/themes/` 目录， 在该目录建立 css 和 js 文件，就可以在 md  文档头部添加 frontmatter 属性`theme`，theme 值与 css 和 js 文件名一致，若无法读取 js 和 css 文件，则使用全局样式文件。
