### ISSUE TITLE
[Bug] windows端切换暗色主题状态条仍为亮色

### ISSUE THREAD

**Issue by Cattle0Horse** [maqi1520/mdx-editor#61]
windows端切换暗色主题状态条仍为亮色
且切换中文语言后, 状态条仍为英文
![Clip_2024-05-20_17-30-52](https://github.com/maqi1520/mdx-editor/assets/107409303/2cb20929-237a-4671-b5f3-26d8ba064a11)

**Comment by maqi1520** [comment]
已知问题，[tauri](https://tauri.app/v1/guides/features/window-customization/) 官方采用的是隐藏 toolbar，使用 HTML 来模拟 mac 的关闭按钮，但这样就丢失了导航功能，这个问题还有待重新设计，目前这样暂时可用。

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases/tag/v0.9.7 版本解决
