### ISSUE TITLE
mac版本没有css和config的选项？

### ISSUE THREAD

**Issue by codegitnoob** [maqi1520/mdx-editor#63]
OS：macbook air M3.
MDX Editor版本：0.9.4

桌面版本没有css和config的选项，试了debug和非debug版本都看不见。
<img width="692" alt="image" src="https://github.com/maqi1520/mdx-editor/assets/64882115/fc7d85e2-7de3-4ee0-9b7b-92901e9871f0">

**Comment by maqi1520** [comment]
![20240527204317](https://github.com/maqi1520/mdx-editor/assets/9312044/504a8645-0e5c-49e4-ab39-885d8c994c40)

需要在` plugins/themes`文件夹下 新建css 和 js 文件，并且在文档头部指定 theme 属性，为 css 或者 js 文件名称。看下截图
