### ISSUE TITLE
最新版本出现bug

### ISSUE THREAD

**Issue by Asura88** [maqi1520/mdx-editor#65]
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/3a14ffb4-e946-46df-97d2-71088acfe308">

mac 电脑

**Comment by maqi1520** [comment]
选择目录后，还可以用吗？可以加我微信 maqi1520

**Comment by maqi1520** [comment]
选择目录后，还可以用吗？可以加我微信 maqi1520

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases/tag/v0.9.6 这个版本可以输入，但是没有自动保存
