### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by ChAoKiLL** [maqi1520/mdx-editor#66]
![PixPin_2024-07-21_09-55-40](https://github.com/user-attachments/assets/ff5c35a4-c497-43ef-a998-07ad9b2bf1a5)
![PixPin_2024-07-21_09-54-57](https://github.com/user-attachments/assets/ae732154-6f70-4801-8a28-867350b7b26f)
![PixPin_2024-07-21_09-58-21](https://github.com/user-attachments/assets/228a80ed-4dee-41a3-b110-fc442931e863)
点击关闭后，界面卡死。无法再点击其他地方

**Comment by maqi1520** [comment]
选择目录后，还可以用吗？可以加我微信 maqi1520

**Comment by ChAoKiLL** [comment]
> 选择目录后，还可以用吗？可以加我微信 maqi1520

已加。没有找到菜单。不点关闭可以用。
![PixPin_2024-07-21_12-03-43](https://github.com/user-attachments/assets/37b46e50-102d-4f17-8a67-4e231426fd3e)

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases/tag/v0.9.6  解决
