### ISSUE TITLE
能否增加保存预设的功能呢？现在只能随时修改css，无法保存多个自定义样式

### ISSUE THREAD

**Issue by white0dew** [maqi1520/mdx-editor#67]
能否增加保存预设的功能呢？现在只能随时修改css，无法保存多个自定义样式

**Comment by maqi1520** [comment]
![image](https://github.com/user-attachments/assets/e55f857f-ec84-4655-a47d-694c8a11c210)
下载最新版，在 文档头部指定 theme 属性，新建 plugins  下 themes 目录，里面存放 css 和 js
