### ISSUE TITLE
为什么 React 组件中某些 dom 元素被删除了？

### ISSUE THREAD

**Issue by zjh1943** [maqi1520/mdx-editor#69]
你好，我在编辑器里写了这样一个 React Component，目的是为了给文本块的四个角加上四个黑色直角。

```jsx
function Aside({ children }) {
  return (
    <div className="aside">
      <div class="corner-container">
        <div class="corner"> </div>
        <div class="corner" style={{ transform: 'rotate(90deg)' }}></div>
      </div>
      {children}
      <div class="corner-container">
        <div class="corner" style={{ transform: 'rotate(270deg)' }}></div>
        <div class="corner" style={{ transform: 'rotate(180deg)' }}></div>
      </div>
    </div>
  )
}
```

当我在 MDX Editor 中功预览的时候，四个直角是正常显示的。如下图：
![image](https://github.com/user-attachments/assets/b0de7b17-9ed4-4e98-a208-94106fe346f5)
但，当我点击 “Copy” 生成微信公众号的 HTML 的时候，发现 div.corner-container 下的元素（div.conrner）不见了。如下图所示：

![image](https://github.com/user-attachments/assets/3ce6a6e8-0d28-44a5-9411-e80ff1627117)

请问这是什么原因？我该如何保留四个黑色直角呢？谢谢！

**Comment by maqi1520** [comment]
这个看起来是个问题，
之前是由于 markdown 编译的时候会产生一些空标签，这些空标签在公众号后台会产生一些空行。因此将空标签删除了。
你可以先使用 span 标签代替，后面会修复这个问题

**Comment by zjh1943** [comment]
好的，谢谢！目前我用 svg 方式达到了同样的效果。

**Comment by maqi1520** [comment]
https://github.com/maqi1520/mdx-editor/releases/tag/v0.9.8
