### ISSUE TITLE
本地客户端可以打开浏览器的样式调整工具吗？

### ISSUE THREAD

**Issue by zjh1943** [maqi1520/mdx-editor#71]
如题，请问有方法可以打开本地客户端的「元素审查工具」或者「样式查看工具」吗？我在调整样式的时候，不知道这个 margin 从哪里来的，很想从样式查看器里看看。因为本地测试的样式和在在线编辑器测试的样式不一样。

![image](https://github.com/user-attachments/assets/9dcd9c99-5c73-468d-980d-6b0d6f0db4f3)

就像这样：

![image](https://github.com/user-attachments/assets/0cf9fed0-d2dd-4b48-a0e2-dadf9cc832e8)

**Comment by maqi1520** [comment]
可以下载 debug 版本

**Comment by zjh1943** [comment]
非常感谢！@maqi1520
