### ISSUE TITLE
win10系统安装后不显示CSS和config标签页

### ISSUE THREAD

**Issue by JiuLiangG** [maqi1520/mdx-editor#75]
![image](https://github.com/user-attachments/assets/7e716fc9-df36-4303-98bb-419110e75610)
web版使用正常，可以正常显示标签页。

问题如图所示，无法显示CSS和config标签页。。
安装包为MDX.Editor_0.9.8_x64-setup-debug.exe
0.9.7版也测试了，也无法显示标签页。
不知道是我电脑问题还是需要通过设置调出标签页。
求解，谢谢。

**Comment by maqi1520** [comment]
看下这个 https://github.com/maqi1520/mdx-editor/discussions/70

**Comment by JiuLiangG** [comment]
好的，谢谢
