### ISSUE TITLE
MDX Error Expected component `Chart` to be defined: you likely forgot to import, pass, or provide it.

### ISSUE THREAD

**Issue by lianquke** [maqi1520/mdx-editor#77]
你好，我是个Windows用户，我第一次安装后，打开就报错
![图片](https://github.com/user-attachments/assets/2317c688-5157-48a7-b4b3-a9ea25a4140a)

**Comment by maqi1520** [comment]
清安装最新版本 https://github.com/maqi1520/mdx-editor/releases/tag/v0.9.8

**Comment by maqi1520** [comment]
将默认的 mdx-editor 删除，这个是老版本创建的，不会自动更新
 或者重新选中一个目录就可以了
