### ISSUE TITLE
MacOS版本复制代码格式不统一

### ISSUE THREAD

**Issue by echoxiangzhou** [maqi1520/mdx-editor#78]
使用最新版本0.9.12的MacOS客户端插入代码块后复制到微信公众号后台格式不统一，如下图：
<img width="600" alt="screenshot-1" src="https://github.com/user-attachments/assets/7ddb56eb-00bc-4fdb-8f4c-4c4cdd7f3644">
但使用Web版本正常。

**Comment by maqi1520** [comment]
全文内容可以分享下吗？

**Comment by echoxiangzhou** [comment]
就这几行代码，仅用作测试。
![ceshi](https://github.com/user-attachments/assets/558b12c0-b7a5-4abb-b546-fdb294aada52)

**Comment by echoxiangzhou** [comment]
Solved.
